In [87]:
import os
import numpy as np
import matplotlib.pyplot as plt
from skimage import io
from scipy.fftpack import fft, dct
import skimage
from skimage.transform import resize
from glob import glob
from sklearn.utils import shuffle
import pandas as pd
import pickle

%matplotlib inline

## Load Data

In [88]:
df1 = pd.read_excel('DB1_B.xlsx')
df2 = pd.read_excel('DB4_B.xlsx')

In [89]:
df1[df1.columns[1:11]],df2[df2.columns[1:11]]

(           0         1  2  3  4  5  6  7  8  9
 0   0.635826  0.364174  0  0  0  0  0  0  0  0
 1   0.635826  0.364174  0  0  0  0  0  0  0  0
 2   0.635826  0.364174  0  0  0  0  0  0  0  0
 3   0.635826  0.364174  0  0  0  0  0  0  0  0
 4   0.635826  0.364174  0  0  0  0  0  0  0  0
 ..       ...       ... .. .. .. .. .. .. .. ..
 75  0.635826  0.364174  0  0  0  0  0  0  0  0
 76  0.635826  0.364174  0  0  0  0  0  0  0  0
 77  0.635826  0.364174  0  0  0  0  0  0  0  0
 78  0.635826  0.364174  0  0  0  0  0  0  0  0
 79  0.635826  0.364174  0  0  0  0  0  0  0  0
 
 [80 rows x 10 columns],
            0         1  2  3  4  5  6  7  8  9
 0   0.635826  0.364174  0  0  0  0  0  0  0  0
 1   0.635826  0.364174  0  0  0  0  0  0  0  0
 2   0.635826  0.364174  0  0  0  0  0  0  0  0
 3   0.635826  0.364174  0  0  0  0  0  0  0  0
 4   0.635826  0.364174  0  0  0  0  0  0  0  0
 ..       ...       ... .. .. .. .. .. .. .. ..
 75  0.635826  0.364174  0  0  0  0  0  0  0  0
 76  0.635826

In [90]:
X1,X2 = df1[df1.columns[1:11]].to_numpy()[:110],df2[df2.columns[1:11]].to_numpy()[:110]

In [91]:
X1.shape,X2.shape

((80, 10), (80, 10))

In [92]:
Y1 = np.array([1 for i in range(X1.shape[0])])
Y2 = np.array([0 for i in range(X2.shape[0])])

In [93]:
Y1.shape,Y2.shape

((80,), (80,))

In [94]:
X = np.power(np.concatenate((X1,X2)),1/5)
X.shape

(160, 10)

In [95]:
Y = np.concatenate((Y1,Y2))
Y.shape

(160,)

In [96]:
X[:10],Y[:10]

(array([[0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.8170

In [97]:
X, Y = shuffle(X, Y, random_state=680)

In [98]:
X[:10],Y[:10]

(array([[0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.81707454, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.91341412, 0.8170

## Train Test Split

In [99]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=13)

## SVM Classifier

In [100]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf =  svm.SVC(kernel='sigmoid')

In [101]:
scores = cross_val_score(clf, X, Y, cv=5)
print("mean = %0.2f , sdtDev = %0.2f" %(scores.mean(),scores.std()))

mean = 0.50 , sdtDev = 0.00


In [102]:
clf.fit(x_train,y_train)

SVC(kernel='sigmoid')

## Predictions

In [103]:
y_pred = clf.predict(x_test)

## Evaluation

In [104]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

In [105]:
#confusion matrix
cnf = confusion_matrix(y_test, y_pred)
cnf

array([[ 0, 18],
       [ 0, 14]], dtype=int64)

In [106]:
precision_recall_fscore_support(y_test,y_pred,average='weighted')

E:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.19140625, 0.4375, 0.266304347826087, None)

In [107]:
print('Accuracy = ',accuracy_score(y_test, y_pred))

Accuracy =  0.4375


## Save model

In [108]:
with open('svmModel.pkl', 'wb') as file:
    pickle.dump(clf, file)